# Generated by Django 3.1.1 on 2020-09-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
