# Generated by Django 3.1.1 on 2020-09-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilopedia', '0006_auto_20200925_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name_tag',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='name_post',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='name_tag',
        ),
    ]
