# Generated by Django 3.1.1 on 2020-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilopedia', '0009_auto_20200930_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=200, verbose_name='факты')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ('fact',),
            },
        ),
    ]
