# Generated by Django 3.1.1 on 2020-10-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilopedia', '0010_funfact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funfact',
            options={'ordering': ('name_fact',), 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
        migrations.RenameField(
            model_name='funfact',
            old_name='fact',
            new_name='name_fact',
        ),
    ]
